### ISSUE TITLE
Make the first PR

### ISSUE THREAD

**Issue by cfr2ak** [Gunforge/TetrisPython#5]
# Let's make the first PR in this repository.

Pull request is not a feature that is served with git itself, but many managed git services contain it.
You need to find _Pull request_ tab inside your Github, Gitlab, Bitbucket, etc.
Pull request is technically only for merging branches. But over that, PR serves the interface and code review system with it. When you make your PR, it is recommended to write What, Why, and How of the code. And you should tag the issues that the PR solves too.

If you want to check what is the best practice, see other OSS repository's PR.

**Comment by cfr2ak** [comment]
So, let's make the first PR from dev/blocks to the master branch.

**Comment by Lyuhitto** [comment]
I checked your request.

**Comment by cfr2ak** [comment]
@Lyuhitto Please close this issue since the PR was made. But when you close an issue which is related to other PR or issues, you should mention the id of them. For this one, Add #4 for Dev/blocks.

**Comment by cfr2ak** [comment]
And, just for sure, you need to leave a comment like 'I'll close this thread since <the reason why you close this issue>'. You can see the button below with an exclamation mark inside a circle with the text 'Close and comment'. Please use that feature when you close this issue. Good luck! 🚀

**Comment by Lyuhitto** [comment]
I'll close this issue since I made [Dev/blocks #4](https://github.com/Gunforge/TetrisPython/pull/4) and it was merged.
Thank you!
